[package]
name = "desync-make"
version = "0.1.0"
authors = ["Krishna Kumar T <krishna.thokala2010@gmail.com>"]
edition = "2018"

[dependencies]
rust-crypto = "0.2.36"
zstd = "0.4.14"
byteorder = "1.3.1"
